# Colors (One Dark)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
#green   = '#98c379'
green   = '#a2ce81'
yellow  = '#d19a66'
#blue    = '#61afef'
blue    = '#0D73CC'
magenta = '#c678dd'
#cyan    = '#56b6c2'
cyan    = '#00cdcd'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
